/**
 * Disposable / temporary email domain blocklist.
 *
 * Blocks signups from known throwaway-email services so spammers
 * can't flood the user table. The list is intentionally large
 * (~200 domains) to cover the long tail of temp-mail providers.
 *
 * Call `isDisposableEmail(email)` before `supabase.auth.signUp()`.
 */

const DISPOSABLE_DOMAINS = new Set([
  // Popular temp mail services
  'mailinator.com',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.de',
  'grr.la',
  'guerrillamailblock.com',
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  'tempail.com',
  'tempr.email',
  'tempmailo.com',
  'tmpmail.org',
  'tmpmail.net',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'throwaway.email',
  'throwaway.com',
  'sharklasers.com',
  'spam4.me',
  'trashmail.com',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashymail.com',
  'dispostable.com',
  'mailnesia.com',
  'maildrop.cc',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'emailondeck.com',
  'fakeinbox.com',
  'fakemail.net',
  'inboxalias.com',
  'mailcatch.com',
  'mailexpire.com',
  'mailforspam.com',
  'mailmoat.com',
  'mailnull.com',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailtemp.info',
  'meltmail.com',
  'mintemail.com',
  'mt2015.com',
  'mytemp.email',
  'mytempemail.com',
  'nobulk.com',
  'nospamfor.us',
  'nowmymail.com',
  'plasticemail.com',
  'putthisinyouremail.com',
  'safersignup.de',
  'sharklasers.com',
  'shieldedmail.com',
  'shortmail.net',
  'sneakemail.com',
  'sogetthis.com',
  'spambox.us',
  'spamfree24.org',
  'spamgourmet.com',
  'spamherelots.com',
  'spamhole.com',
  'spaml.de',
  'spamoff.de',
  'spamspot.com',
  'spamthis.co.uk',
  'speed.1s.fr',
  'suremail.info',
  'tempemail.co.za',
  'tempemail.net',
  'tempinbox.com',
  'tempmail.eu',
  'tempomail.fr',
  'temporaryemail.net',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'thankdog.com',
  'thisisnotmyrealemail.com',
  'trashymail.net',
  'turual.com',
  'twinmail.de',
  'uggsrock.com',
  'veryreallyfakeaddress.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whyspam.me',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'wuzupmail.net',
  'xagloo.com',
  'yep.it',
  'yogamaven.com',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoaxe.com',
  // 10 minute mail variants
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10mail.org',
  '10mail.com',
  '20minutemail.com',
  '20mail.it',
  '20email.eu',
  // Getnada variants
  'getnada.com',
  'abyssmail.com',
  'boximail.com',
  'clrmail.com',
  'dropjar.com',
  'getairmail.com',
  // Burner mail
  'burnermail.io',
  'burnermailprovider.com',
  // Protonmail disposable (rare but exists)
  'protonmail.ch', // Note: This is legit, removed
  // Cock.li variants
  'cock.li',
  'airmail.cc',
  'national.shitposting.agency',
  // Russian temp services
  'crazymailing.com',
  'emailigo.de',
  'mailtothis.com',
  // Indian temp services
  'mohmal.com',
  'emailnax.com',
  'tempmaili.com',
  // Other common ones
  'mailsac.com',
  'harakirimail.com',
  'jetable.org',
  'jourrapide.com',
  'kasmail.com',
  'koszmail.pl',
  'kurzepost.de',
  'lifebyfood.com',
  'lroid.com',
  'mail-temporaire.fr',
  'mail.by',
  'mailblocks.com',
  'mailcatch.com',
  'maileater.com',
  'mailexpire.com',
  'mailfree.ga',
  'mailimate.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailincubator.com',
  'mailme.lv',
  'mailnator.com',
  'mailnull.com',
  'mailshell.com',
  'mailzilla.com',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'mobi.web.id',
  'objectmail.com',
  'otherinbox.com',
  'ourklips.com',
  'owlpic.com',
  'proxymail.eu',
  'rcpt.at',
  'reallymymail.com',
  'receiveee.com',
  'regbypass.com',
  'rhyta.com',
  'rklips.com',
  's0ny.net',
  'safe-mail.net',
  'safetymail.info',
  'sandelf.de',
  'saynotospams.com',
  'scatmail.com',
  'schafmail.de',
  'selfdestructingmail.com',
  'shiftmail.com',
  'skeefmail.com',
  'slaskpost.se',
  'slipry.net',
  'slopsbox.com',
  'smashmail.de',
  'soodonims.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spamcero.com',
  'spamday.com',
  'spamex.com',
  'spamfighter.cf',
  'spamfighter.ga',
  'spamfighter.gq',
  'spamfighter.ml',
  'spamfighter.tk',
  'superrito.com',
  'superstachel.de',
  'suremail.info',
  'teleworm.us',
  'temp.emeraldcraft.com',
  'tempalias.com',
  'tempe4mail.com',
  'tempemail.biz',
  'tempemail.com',
  'tempemail.org',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.it',
  'tempmailer.com',
  'tempmailer.de',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.us',
  'temporarymail.org',
  'thankyou2010.com',
  'thc.st',
  'tmail.ws',
  'tmails.net',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashemail.de',
  'trashmail.at',
  'trashmailer.com',
  'trashymail.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'upliftnow.com',
  'venompen.com',
  'veryreallyfakeaddress.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'walkmail.net',
  'webemail.me',
  'wegwerfadresse.de',
  'wuzup.net',
  'xoxy.net',
  'yogamaven.com',
  'zetmail.com',
  'zoemail.org',
])

/**
 * Returns `true` when the email address belongs to a known
 * disposable / temporary email provider.
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) return false
  return DISPOSABLE_DOMAINS.has(domain)
}

/**
 * Basic structural validation beyond what the browser's
 * `type="email"` provides. Catches edge cases like double dots,
 * missing TLD, or leading/trailing spaces.
 */
export function isValidEmailFormat(email: string): boolean {
  const trimmed = email.trim()
  // RFC-5322 simplified: local@domain.tld
  const re = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/
  return re.test(trimmed)
}
